config/routes.rb
Rails.application.routes.draw do

  get 'new-session/:token' => "session#token", as: :new_session

  root to: 'emails#index'

  resources :emails do
    get 'render_html', on: :member
    get 'render_preview', on: :member
    post 'archive', on: :member
    post 'unarchive', on: :member

    get 'archived', on: :collection
    post 'live_preview', on: :collection
  end

  get 'export/:token' => 'export#token', as: :token_export

  resources :templates

end

app/models/available_template.rb
class AvailableTemplate
  def self.all
    Template.order('title ASC').all || []
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :template
  validates :template, presence: true

  validates_inclusion_of :is_archived, in: [true, false]

  before_create do
    self.token = SecureRandom.urlsafe_base64(30)
  end

  after_initialize do
    if self.new_record?
      self.is_archived = false
    end
  end

  scope :archived,     -> { where(is_archived: true)  }
  scope :not_archived, -> { where(is_archived: false) }

  def render
    EmailRenderer.new(email: self).render
  end

  def is_archived?
  	self.is_archived == true
  end

end

app/models/template.rb
class Template < ActiveRecord::Base
  has_many :emails
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authorize!
    token = cookies.signed[:token]
    if TokenAuthentication.valid?(token)
      # everything okay
    else
      cookies.delete(:token)
      render text: "Unauthorized", status: 422
      return false
    end
  end

end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_email, only: [:show, :edit, :update, :destroy, :render_html, :render_preview, :archive, :unarchive]

  before_action {
    authorize!
  }

  def render_html
    render html: @email.render
  end

  def render_preview
    render inline: @email.render
  end

  def live_preview
    template = Template.find_by(id: params[:template_id])
    if template.nil?
      render json: { message: 'Invalid Template'}, status: 422 and return false
    end

    email = Email.new(template: template, content: params[:content])
    render json: {
      html: email.render
    }
  end

  # GET /emails
  # GET /emails.json
  def index
    @emails = Email.not_archived.order('updated_at DESC').all
  end

  def archived
    @emails = Email.archived.order('updated_at DESC').all
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
  end

  # GET /emails/new
  def new
    @email = Email.new
  end

  # GET /emails/1/edit
  def edit
  end

  def archive
    @email.is_archived = true
    @email.save!

    redirect_to emails_path
  end

  def unarchive
    @email.is_archived = false
    @email.save!

    redirect_to emails_path
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(email_params)

    respond_to do |format|
      if @email.save
        format.html { redirect_to edit_email_path(@email), notice: 'Email was successfully created.' }
        format.json { render :show, status: :created, location: @email }
      else
        format.html { render :new }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emails/1
  # PATCH/PUT /emails/1.json
  def update
    respond_to do |format|
      if @email.update(email_params)
        format.html { redirect_to edit_email_path(@email), notice: 'Email was successfully updated.' }
        format.json { render :show, status: :ok, location: @email }
      else
        format.html { render :edit }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @email.destroy
    respond_to do |format|
      format.html { redirect_to emails_url, notice: 'Email was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email
      @email = Email.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_params
      params.require(:email).permit(:template_id, :title, :content)
    end
end

app/controllers/export_controller.rb
class ExportController < ApplicationController
  def token
    email = Email.find_by(token: params[:token])
    if email.present?
      render inline: email.render
    else
      render text: "Not Found", status: 404
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def token
    token = params[:token]

    if TokenAuthentication.valid?(token)
      cookies.signed[:token] = token
      redirect_to root_path
    else
      render text: "Unauthorized", status: 422
    end
  end

end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: [:show, :edit, :update, :destroy]

  before_action {
    authorize!
  }

  # GET /templates
  # GET /templates.json
  def index
    @templates = Template.all
  end

  # GET /templates/1
  # GET /templates/1.json
  def show
  end

  # GET /templates/new
  def new
    @template = Template.new
  end

  # GET /templates/1/edit
  def edit
  end

  # POST /templates
  # POST /templates.json
  def create
    @template = Template.new(template_params)

    respond_to do |format|
      if @template.save
        format.html { redirect_to templates_url, notice: 'Template was successfully created.' }
        format.json { render :show, status: :created, location: @template }
      else
        format.html { render :new }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /templates/1
  # PATCH/PUT /templates/1.json
  def update
    respond_to do |format|
      if @template.update(template_params)
        format.html { redirect_to templates_url, notice: 'Template was successfully updated.' }
        format.json { render :show, status: :ok, location: @template }
      else
        format.html { render :edit }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /templates/1
  # DELETE /templates/1.json
  def destroy
    @template.destroy
    respond_to do |format|
      format.html { redirect_to templates_url, notice: 'Template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template
      @template = Template.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def template_params
      params.require(:template).permit(:title, :header, :footer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/export_helper.rb
module ExportHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/export/token.html.erb
<h1>Export#token</h1>
<p>Find me in app/views/export/token.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Pony</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
<%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <b>Pony</b></a>
    </div>
    <div id="navbar" class="collapse navbar-collapse pull-right">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Create a New Email', new_email_path %></li>
        <li><%= link_to "Emails", emails_path %></li>
        <li><%= link_to "Templates", templates_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/session/token.html.erb
<h1>Session#token</h1>
<p>Find me in app/views/session/token.html.erb</p>

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <% @template.errors.full_messages.each do |message| %>
        <h2><%= message %></h2>
      <% end %>
    </div>
  <% end %>


  <div class="pony-section pony-spacer-lg">
  <div class="container">
    <div class="row pony-spacer-md">
      <div class="col-md-12">
        <h4>Details</h4>
      </div>
    </div>

    <form class="form-horizontal">
      <div class="row pony-spacer-sm">
        <div class="form-group form-group-lg">
          <label class="col-sm-1">Title</label>
          <div class="col-sm-11">
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="row pony-spacer-sm">
        <div class="form-group form-group-lg">
          <label class="col-sm-1">Header</label>
          <div class="col-sm-11">
            <%= f.text_area :header, class: 'form-control', label: false, rows: "10" %>
          </div>
        </div>
      </div>
      <div class="row pony-spacer-sm">
        <div class="form-group form-group-lg">
          <label class="col-sm-1">Footer</label>
          <div class="col-sm-11">
           <%= f.text_area :footer, class: 'form-control', label: false, rows: "10" %>
          </div>
        </div>
      </div>
      <div class="row pony-spacer-sm">
        <div class="form-group form-group-lg">
          <div class="col-md-9">
            <!-- negative space -->
          </div>
          <div class="col-md-3">
            <%= f.button :submit , class: "btn btn-default btn-lg btn-block" %>
          </div>
        </div>
      </div>
    </form>
  </div><!-- /.container -->
</div>

<% end %>

app/views/templates/edit.html.erb
<div class="pony-section pony-topper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Editing Template</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi in rutrum sem. Cras molestie, lectus a lobortis interdum, diam mauris ultricies felis.</p>
      </div>
      <div class="col-md-3">
      </div>
      <div class="col-md-3">
      </div>
    </div>
  </div><!-- /.container -->
</div>

<%= render 'form' %>

app/views/templates/index.html.erb
<div class="pony-section pony-topper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Templates</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi in rutrum sem. Cras molestie, lectus a lobortis interdum, diam mauris ultricies felis.</p>
      </div>
      <div class="col-md-3">
      </div>
      <div class="col-md-3">
        <%= link_to 'Create New Template', new_template_path, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
  </div><!-- /.container -->
</div>

<div class="klax-section klax-spacer-lg">
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th>Created</th>
          <th>Title</th>
          <th colspan="14"></th>
        </tr>
      </thead>

      <tbody>
        <% @templates.each do |template| %>
          <tr>
            <td><%= template.created_at.strftime("%m/%d/%Y at %I:%M%p") %></td>
            <td><%= template.title %></td>
            <td><%= link_to 'Edit', edit_template_path(template), class: 'btn btn-default btn-block' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/templates/new.html.erb
<div class="pony-section pony-topper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>New Template</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi in rutrum sem. Cras molestie, lectus a lobortis interdum, diam mauris ultricies felis.</p>
      </div>
      <div class="col-md-3">
      </div>
      <div class="col-md-3">
      </div>
    </div>
  </div><!-- /.container -->
</div>

<%= render 'form' %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @template.title %>
</p>

<p>
  <strong>Header:</strong>
  <%= @template.header %>
</p>

<p>
  <strong>Footer:</strong>
  <%= @template.footer %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>